name: "2021"

on:
  push:
    paths:
      - ".github/workflows/2021.yml"
      - "2021/**/*.*"
  pull_request:
    paths:
      - ".github/workflows/2021.yml"
      - "2021/**/*.*"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.4"

      # - name: Run
      #   run: |
      #     cd 2021

      #     availableDay=("1" "2" "3" "4" "5" "6" "7")

      #     for day in "${availableDay[@]}"; do
      #       cd "Day $day"

      #       # JS
      #       cd Javascript
      #       time node index.js > /dev/null
      #       cd ..

      #       # lua
      #       cd lua
      #       time lua index.lua > /dev/null
      #       cd ..

      #       cd ..
      #     done

      #     echo Have fun! Advent of Code!

      - name: Run
        continue-on-error: true
        run: |
          cd 2021

          availableDay=("1" "2" "3" "4" "5" "6" "7")

          for day in "${availableDay[@]}"; do
            cd "Day $day"/lua
            time lua index.lua > /dev/null
            cd ../../
          done

          echo Have fun! Advent of Code!

      - name: Run
        continue-on-error: true
        run: |
          cd 2021

          availableDay=("1" "2" "3" "4" "5" "6" "7")

          for day in "${availableDay[@]}"; do
            cd "Day $day"/Javascript
            time node index.js > /dev/null
            cd ../../
          done

          echo Have fun! Advent of Code!
