name: "2022"

on:
  push:
  pull_request:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Run
        run: |
          cd 2022

          cargo run -r -p day-1 > /dev/null
          cargo run -r -p day-2 > /dev/null
          cargo run -r -p day-3 > /dev/null

          echo Have fun! Advent of Code!
